--- #YAML:1.0
name:               Dancer-Template-TemplateFlute
version:            0.0024
abstract:           Template::Flute wrapper for Dancer
author:
    - Stefan Hornburg (Racke) <racke@linuxia.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dancer:           0
    Template::Flute:  0.0023
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
